# ============================================================
#  Configuraci\u00c3\u00b3n de conexi\u00c3\u00b3n - Oracle 10g XE
#  Plataforma de Pr\u00c3\u00a1cticas Pedag\u00c3\u00b3gicas
# ============================================================
db.driver=oracle.jdbc.OracleDriver
db.url=jdbc:oracle:thin:@192.168.254.215:1521:orcl
db.user=proyecto4137
db.password=proyecto4137
db.pool.size=10
 
#para conectar local
#db.driver=oracle.jdbc.OracleDriver
##db.url=jdbc:oracle:thin:@localhost:1521:XE
#db.user=hola
#db.password=hola
#db.pool.size=10
